### ISSUE TITLE
No field of name bins_PCA

### ISSUE THREAD

**Issue by MartinStevko** [marcelTBI/CNV_data#2]
In `add_pca.py` module on line 74 python returns value error with message 'no field of name bins_PCA'.
![image](https://user-images.githubusercontent.com/28576351/87397216-4758ab80-c5b4-11ea-9453-efbddab27046.png)

**Comment by marcelTBI** [comment]
solved by commit #1e2c0bfb44a32987e39ff9b53f9bd463e1ee5cff
