### ISSUE TITLE
Problem in handling Negative values in the loess-normalized bin data 

### ISSUE THREAD

**Issue by meghavarshney** [marcelTBI/CNV_data#5]
How to address the presence of negative values in the loess-normalized bin data when conducting PCA training using this tool. These negative values are impacting the PCA training process, and how to handle them effectively within the tool's framework

**Comment by marcelTBI** [comment]
I know that there is a small number of negative values in loess-normalized bin data, but we did not compensate or treat them any differently. Maybe we should. However, there is only a very small number of negative value bins (usually up to 10 bins), so I believe the impact of treating them any differently would be very minor.
